// Temporary mock data — will be replaced with Supabase queries in Phase 1.8
// Re-exported from the original hooks/useMockData for now

import { Product, Seller, StoneType, Origin, Finish, SizeType, PriceUnit, UseCase } from '@/types';

const sellers: Seller[] = [
    { id: 1, name: 'Rajasthan Marble Emporium', location: 'Jaipur, Rajasthan', isVerified: true, verificationLevel: 'Gold', rating: 4.8, reviews: 152, contact: { phone: '9876543210', email: 'sales@rajasthanmarble.com', whatsapp: '+919876543210' } },
    { id: 2, name: 'Deccan Granite Exports', location: 'Bangalore, India', isVerified: true, verificationLevel: 'Quarry-Direct', rating: 4.5, reviews: 89, contact: { phone: '9876543211', email: 'contact@indiangranite.com' } },
    { id: 3, name: 'Makrana Pure White Heritage', location: 'Makrana, Rajasthan', isVerified: true, verificationLevel: 'Quarry-Direct', rating: 4.9, reviews: 210, contact: { phone: '9876543212', email: 'info@makranawhite.com' } },
    { id: 4, name: 'Global Stone & Craft', location: 'Delhi, India', isVerified: true, verificationLevel: 'Basic', rating: 4.2, reviews: 45, contact: { phone: '9876543213', email: 'support@globalstone.com' } },
    { id: 5, name: 'Euro-Import Marble Hub', location: 'India', isVerified: true, verificationLevel: 'Gold', rating: 4.9, reviews: 320, contact: { phone: '9876543214', email: 'orders@italianmarblehub.com' } },
];

export const products: Product[] = [
    {
        id: 1,
        name: 'Royal Statuario Italian Marble',
        stoneType: StoneType.MARBLE,
        origin: Origin.ITALY,
        finish: Finish.POLISHED,
        size: { type: SizeType.SLAB, dimensions: '9ft x 6ft' },
        thickness: '20mm',
        color: 'White with Bold Grey Veining',
        price: 1250,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 500,
        stock: 4500,
        images: [
            'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=2000&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=2000&auto=format&fit=crop'
        ],
        seller: sellers[4],
        description: 'The pinnacle of luxury. Statuario marble features a bright white background with dramatic grey veining. Ideal for high-end master bathrooms and feature walls.',
        useCases: [UseCase.HOME, UseCase.HOTEL, UseCase.COMMERCIAL],
        hasInspectionReport: true,
    },
    {
        id: 2,
        name: 'Imperial Red Granite (Premium)',
        stoneType: StoneType.GRANITE,
        origin: Origin.INDIA,
        finish: Finish.POLISHED,
        size: { type: SizeType.SLAB, dimensions: '10ft x 3.5ft' },
        thickness: '18mm',
        color: 'Deep Red with Black Crystals',
        price: 320,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 1000,
        stock: 15000,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=2000&auto=format&fit=crop'],
        seller: sellers[1],
        description: 'Highly durable and weather-resistant granite. Its deep red hue adds warmth and luxury to kitchen countertops and exterior wall cladding.',
        useCases: [UseCase.COMMERCIAL, UseCase.HOME, UseCase.INFRASTRUCTURE],
        hasInspectionReport: true,
    },
    {
        id: 3,
        name: 'Makrana Albeta White',
        stoneType: StoneType.MARBLE,
        origin: Origin.MAKRANA,
        finish: Finish.POLISHED,
        size: { type: SizeType.SLAB, dimensions: '8ft x 4ft' },
        thickness: '16mm',
        color: 'Milky White with Fine Grey Lines',
        price: 450,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 200,
        stock: 8000,
        images: ['https://images.unsplash.com/photo-1615971677499-5467cbab01c0?q=80&w=2000&auto=format&fit=crop'],
        seller: sellers[2],
        description: 'The same marble variety used in architectural wonders. Albeta is known for its purity and longevity, lasting for centuries without yellowing.',
        useCases: [UseCase.TEMPLE, UseCase.HOME, UseCase.HOTEL],
        hasInspectionReport: true,
    },
    {
        id: 4,
        name: 'Dholpur Beige Sandstone',
        stoneType: StoneType.SANDSTONE,
        origin: Origin.RAJASTHAN,
        finish: Finish.NATURAL,
        size: { type: SizeType.TILE, dimensions: '2ft x 1ft' },
        thickness: '25mm',
        color: 'Soft Sand Beige',
        price: 85,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 5000,
        stock: 50000,
        images: ['https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=2000&auto=format&fit=crop'],
        seller: sellers[0],
        description: 'A favorite for heritage restoration and landscaping. Dholpur Beige offers a natural, slip-resistant surface perfect for outdoor courtyards.',
        useCases: [UseCase.INFRASTRUCTURE, UseCase.TEMPLE, UseCase.DECORATION],
    },
    {
        id: 5,
        name: 'Grey William Marble',
        stoneType: StoneType.MARBLE,
        origin: Origin.ITALY,
        finish: Finish.MATTE,
        size: { type: SizeType.SLAB, dimensions: '9ft x 5ft' },
        thickness: '20mm',
        color: 'Sophisticated Smoky Grey',
        price: 480,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 300,
        stock: 2200,
        images: ['https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?q=80&w=2000&auto=format&fit=crop'],
        seller: sellers[4],
        description: 'A contemporary choice for modern apartments. The matte finish provides a subtle, non-reflective elegance to interior flooring.',
        useCases: [UseCase.HOME, UseCase.HOTEL],
    },
    {
        id: 6,
        name: 'Absolute Black Granite',
        stoneType: StoneType.GRANITE,
        origin: Origin.INDIA,
        finish: Finish.LEATHER,
        size: { type: SizeType.SLAB, dimensions: '10ft x 4ft' },
        thickness: '20mm',
        color: 'Solid Pure Black',
        price: 240,
        priceUnit: PriceUnit.SQ_FT,
        minOrderQty: 500,
        stock: 20000,
        images: ['https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=2000&auto=format&fit=crop'],
        seller: sellers[1],
        description: 'The industry standard for premium black surfaces. The leather finish provides a unique tactile texture that is stain-resistant.',
        useCases: [UseCase.COMMERCIAL, UseCase.HOME, UseCase.HOTEL],
        hasInspectionReport: true,
    }
];

export { sellers };

export const useMockData = () => {
    return { products, sellers };
};
